[workspace]
members = [
        "definitions",
        "hla_cli",
        "bio_utils",
        "haplotyper",
        "partial_order_alignment",
        "sandbox",
        "histgram_viz",
        "mcl",
]