[package]
name = "haplotyper"
version = "0.1.0"
authors = ["ban-m <ban-m@g.ecc.u-tokyo.ac.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
definitions = {path = "../definitions"}
log = "*"
env_logger = "*"
bio_utils = {path = "../bio_utils"}
serde = {version = "1.0", features = ["derive"]}
rayon = "*"
rand = "*"
rand_xoshiro = "*"
poa_hmm = {path = "../partial_order_alignment"}
nalgebra  = "*"
